vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            uri_prefix: /images/properties
            upload_destination: '%kernel.project_dir%/public/images/properties' # nom du dossier ou seront stocké les images
            namer: Vich\UploaderBundle\Naming\UniqidNamer # permet de donner au nom de l'image uploadée un id unique 
    
