# Fichier qui sert à définir les routes de l'application (mais dans la notre on utilise les annotation pour le rooting)

#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# Route pour la déconnexion (qui ne necessite pas de controlleur, ni de vue)
logout:
  path: /logout